name: DEVOPS - Database Migration with Liquibase

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: minha_base
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Code Download
        uses: actions/checkout@v4

      - name: Setting Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setting cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Add Postgres to /etc/hosts
        run: |
          echo "127.000.1 postgres" | sudo tee -a /etc/hosts

      - name: waiting Postgres To Be Ready
        run: |
          for i in {1..15}; do
            nc -zv postgres 5432 && echo "✅ PostgreSQL is ready!" && exit 0
            echo "⏳ Waiting for PostgreSQL..."
            sleep 5
          done
          echo "❌ PostgreSQL did not start in time." && exit 1
      
      - name: Build and Run Liquibase
        run: mvn -B clean compile liquibase:update